export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const DOWNLOAD_FULL_REGISTRY_STARTED = 'DOWNLOAD_FULL_REGISTRY_STARTED';
export const DOWNLOAD_FULL_REGISTRY_FINISHED = 'DOWNLOAD_FULL_REGISTRY_FINISHED';
export const DOWNLOAD_FULL_REGISTRY_FAILED = 'DOWNLOAD_FULL_REGISTRY_FAILED';
export const UPDATE_DOWNLOAD_PROGRESS = 'UPDATE_DOWNLOAD_PROGRESS';
