export const RECEIVE_ALL_SERVICES = 'RECEIVE_ALL_SERVICES';
export const RECEIVE_SORTING = 'RECEIVE_SORTING';
export const RECEIVE_PAGING = 'RECEIVE_PAGING';
export const UPDATE_NEWSERVICE_NAME = 'UPDATE_NEWSERVICE_NAME';

export const UPDATE_MYSERVICE_NAME = 'UPDATE_MYSERVICE_NAME';
export const UPDATE_MYSERVICE_COMPETENTAUTHORITY = 'UPDATE_MYSERVICE_COMPETENTAUTHORITY';
export const UPDATE_MYSERVICE_ISSUBSIDY = 'UPDATE_MYSERVICE_ISSUBSIDY';

export const SET_MYSERVICE = 'SET_MYSERVICE';
export const RESET_NEWSERVICE = 'RESET_NEWSERVICE';
export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const LOADING_ON = 'LOADING_ON';
export const LOADING_OFF = 'LOADING_OFF';
export const DUMMY = 'ADD_TO_CART';

export const SET_REQUIRED_FIELD_STATUS = 'SET_REQUIRED_FIELD_STATUS';
export const REMOVE_REQUIRED_FIELD_STATUS = 'REMOVE_REQUIRED_FIELD_STATUS';
export const CLEAR_REQUIRED_FIELDS = 'CLEAR_REQUIRED_FIELDS';
