namespace RoadRegistry.BackOffice.FeatureToggles;

public sealed record UseDefaultRoadNetworkFallbackForOutlinedRoadSegmentsFeatureToggle(bool FeatureEnabled) : ApplicationFeatureToggle(FeatureEnabled);
