namespace RoadRegistry.BackOffice.FeatureToggles;

public sealed record UseGradeSeparatedJunctionLowerRoadSegmentEqualsUpperRoadSegmentValidationFeatureToggle(bool FeatureEnabled) : ApplicationFeatureToggle(FeatureEnabled);
