namespace RoadRegistry.BackOffice.FeatureToggles;

public sealed record UseValidateRoadSegmentIntersectionsWithMissingGradeSeparatedJunctionFeatureToggle(bool FeatureEnabled) : ApplicationFeatureToggle(FeatureEnabled);
