<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\.build\Be.Vlaanderen.Basisregisters.Build.Pipeline\Content\Be.Vlaanderen.Basisregisters.Build.Pipeline.Settings.App.props" />

  <PropertyGroup>
    <RootNamespace>RoadRegistry.BackOffice.Handlers.Sqs.Lambda.CodeGen</RootNamespace>
    <AssemblyName>RoadRegistry.BackOffice.Handlers.Sqs.Lambda.CodeGen</AssemblyName>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RoadRegistry.BackOffice.Handlers.Sqs.Lambda\RoadRegistry.BackOffice.Handlers.Sqs.Lambda.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
</Project>
