version: '3.8'

services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: road-mssql
    ports:
      - 21433:1433
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: E@syP@ssw0rd
      MSSQL_MEMORY_LIMIT_MB: 1000
      MSSQL_PID: Standard
    volumes:
      - road-mssql-data:/var/opt/mssql
      - ../src/RoadRegistry.BackupDatabase/filled:/var/lib/backup

  import-backup:
    build: ../src/RoadRegistry.BackupDatabase/filled
    container_name: road-mssql-import-backup
    depends_on:
      - mssql
    volumes:
      - ../src/RoadRegistry.BackupDatabase/filled:/var/lib/backup
    profiles:
      - seed

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    environment:
      SERVICES: s3,sqs,lambda,dynamodb,logs
      DOCKER_HOST: unix:///var/run/docker.sock
      LAMBDA_EXECUTOR: docker-reuse
      LAMBDA_REMOTE_DOCKER: true
      LAMBDA_REMOVE_CONTAINERS: true
      DEBUG: true
      PORT_WEB_UI: 8081
      SQS_ENDPOINT_STRATEGY: path
      AWS_REGION: eu-west-1
    volumes:
      - type: bind
        source: ../.localstack/data
        target: /var/lib/localstack
      - ../.localstack/s3data:/usr/local/lib/localstack
      - ../.localstack/init:/etc/localstack/init
      - ../.localstack/lambda:/etc/localstack/lambda
      - /var/run/docker.sock:/var/run/docker.sock

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
    - "9010:9000"
    - "9011:9001"
    environment:
      MINIO_ACCESS_KEY: Q3AM3UQ867SPQQA43P2F
      MINIO_SECRET_KEY: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
    volumes:
    - minio-data:/data
    command: server --console-address :9001 /data

  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - 5341:80
    environment:
      ACCEPT_EULA: 'Y'
    volumes:
      - seq-data:/data

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    ports:
      - 9092:9092
    depends_on:
      - kafka-admin
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: kafka-admin:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-admin:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: kafka-admin
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  postgresql:
    build: ./postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: E@syP@ssw0rd
    ports:
      - 29050:5432

  postgresql-admin:
    image: adminer
    container_name: postgresql-admin
    ports:
      - 8081:8080

  wiremock:
    image: rodolpheche/wiremock:2.29.1
    container_name: wiremock
    volumes:
      - ../wiremock/mappings:/home/wiremock/mappings
    ports:
      - 8080:8080
  
  ticketing-service:
    image: 830031229216.dkr.ecr.eu-west-1.amazonaws.com/ticketing-service/ticketing:1.16.2
    container_name: ticketing-service
    depends_on:
      - postgresql
      - postgresql-admin
    environment:
      BASEURL: http://localhost:9100
      CONNECTIONSTRINGS__MARTEN: Server=postgresql;Port=5432;Database=ticketing;Userid=sa;Password=E@syP@ssw0rd;Trust Server Certificate=true;Timeout=120
      DOTNET_ENVIRONMENT: Development
      #CORS__0: http://localhost:3000
      #CORS__1: http://localhost:5000
    ports:
      - 9100:9000

  # identity-server:
  #    #image: ghcr.io/informatievlaanderen/identity-server-fake:latest
  #    build: ../src/Be.Vlaanderen.Basisregisters.IdentityServer
  #    container_name: identity-server
  #    volumes:
  #      - ../.identityserver:/home/identityserver
  #    ports:
  #      - 5050:80

volumes:
  road-mssql-data:
    name: road-mssql-data
    external: true
  seq-data:
    name: seq-data
    external: true
  minio-data:

networks:
  default:
    name: road-registry-network
    external: true
