// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using RoadRegistry.Extracts.Schema;

#nullable disable

namespace RoadRegistry.Extracts.Schema.Migrations
{
    [DbContext(typeof(ExtractsDbContext))]
    [Migration("20251201102250_AddZipArchiveWriterVersion")]
    partial class AddZipArchiveWriterVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Be.Vlaanderen.Basisregisters.ProjectionHandling.Runner.ProjectionStates.ProjectionStateItem", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DesiredState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DesiredStateChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Position")
                        .HasColumnType("bigint");

                    b.HasKey("Name");

                    b.ToTable("ProjectionStates", "RoadRegistryExtracts");
                });

            modelBuilder.Entity("RoadRegistry.Extracts.Schema.ExtractDownload", b =>
                {
                    b.Property<Guid>("DownloadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Closed")
                        .HasColumnType("bit");

                    b.Property<Geometry>("Contour")
                        .IsRequired()
                        .HasColumnType("Geometry");

                    b.Property<int>("DownloadStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DownloadedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExtractRequestId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsInformative")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("RequestedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UploadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("UploadStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UploadedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ZipArchiveWriterVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("V2");

                    b.HasKey("DownloadId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("DownloadId"));

                    b.HasIndex("ExtractRequestId");

                    b.ToTable("ExtractDownloads", "RoadRegistryExtracts");
                });

            modelBuilder.Entity("RoadRegistry.Extracts.Schema.ExtractRequest", b =>
                {
                    b.Property<string>("ExtractRequestId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("CurrentDownloadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalRequestId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("RequestedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ExtractRequestId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("ExtractRequestId"));

                    b.HasIndex("CurrentDownloadId");

                    b.ToTable("ExtractRequests", "RoadRegistryExtracts");
                });
#pragma warning restore 612, 618
        }
    }
}
