services:
 road-marten-postgres:
   image: postgis/postgis:17-master
   ports:
     - "5440:5432"
   volumes:
     - type: tmpfs
       target: /var/lib/postgresql/data
     - type: tmpfs
       target: /dev/shm
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
