// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoadRegistry.WmsWfsV1Inwinning;

#nullable disable

namespace RoadRegistry.WmsWfsV1Inwinning.Migrations
{
    [DbContext(typeof(WmsWfsV1InwinningContext))]
    partial class WmsWfsV1InwinningContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Be.Vlaanderen.Basisregisters.ProjectionHandling.Runner.ProjectionStates.ProjectionStateItem", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DesiredState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DesiredStateChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Position")
                        .HasColumnType("bigint");

                    b.HasKey("Name");

                    b.ToTable("ProjectionStates", "RoadRegistry");
                });

            modelBuilder.Entity("RoadRegistry.WmsWfsV1Inwinning.Records.CompletedRoadNodeRecord", b =>
                {
                    b.Property<int>("WK_OIDN")
                        .HasColumnType("int");

                    b.HasKey("WK_OIDN");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("WK_OIDN"));

                    b.ToTable("CompletedRoadNodes", "RoadRegistry");
                });

            modelBuilder.Entity("RoadRegistry.WmsWfsV1Inwinning.Records.CompletedRoadSegmentRecord", b =>
                {
                    b.Property<int>("WS_OIDN")
                        .HasColumnType("int");

                    b.HasKey("WS_OIDN");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("WS_OIDN"));

                    b.ToTable("CompletedRoadSegments", "RoadRegistry");
                });

            modelBuilder.Entity("RoadRegistry.WmsWfsV1Inwinning.Records.V1WfsRoadNodeRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("objectId");

                    b.Property<bool>("IsV2")
                        .HasColumnType("bit")
                        .HasColumnName("IsV2");

                    b.HasKey("Id");

                    b.ToTable("Wegknoop", "RoadRegistryWfsData", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("RoadRegistry.WmsWfsV1Inwinning.Records.V1WfsRoadSegmentRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("objectId");

                    b.Property<bool>("IsV2")
                        .HasColumnType("bit")
                        .HasColumnName("IsV2");

                    b.HasKey("Id");

                    b.ToTable("Wegsegment", "RoadRegistryWfsData", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("RoadRegistry.WmsWfsV1Inwinning.Records.V1WmsEuropeanRoadRecord", b =>
                {
                    b.Property<int>("EU_OIDN")
                        .HasColumnType("int")
                        .HasColumnName("EU_OIDN");

                    b.Property<bool>("IsV2")
                        .HasColumnType("bit")
                        .HasColumnName("IsV2");

                    b.Property<int>("WS_OIDN")
                        .HasColumnType("int")
                        .HasColumnName("WS_OIDN");

                    b.HasKey("EU_OIDN");

                    b.ToTable("EuropeseWeg", "RoadRegistryWmsData", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("RoadRegistry.WmsWfsV1Inwinning.Records.V1WmsNationalRoadRecord", b =>
                {
                    b.Property<int>("NW_OIDN")
                        .HasColumnType("int")
                        .HasColumnName("NW_OIDN");

                    b.Property<bool>("IsV2")
                        .HasColumnType("bit")
                        .HasColumnName("IsV2");

                    b.Property<int>("WS_OIDN")
                        .HasColumnType("int")
                        .HasColumnName("WS_OIDN");

                    b.HasKey("NW_OIDN");

                    b.ToTable("NationaleWeg", "RoadRegistryWmsData", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("RoadRegistry.WmsWfsV1Inwinning.Records.V1WmsRoadSegmentRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("wegsegmentID");

                    b.Property<bool>("IsV2")
                        .HasColumnType("bit")
                        .HasColumnName("IsV2");

                    b.HasKey("Id");

                    b.ToTable("wegsegmentDenorm", "RoadRegistryWmsData", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
