// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using RoadRegistry.WmsWfsV2.Schema;

#nullable disable

namespace RoadRegistry.WmsWfsV2.Schema.Migrations
{
    [DbContext(typeof(WmsWfsV2Context))]
    [Migration("20260731081940_OngelijkgrondseKruisingenViewOnlyWithGeometry")]
    partial class OngelijkgrondseKruisingenViewOnlyWithGeometry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Be.Vlaanderen.Basisregisters.ProjectionHandling.Runner.ProjectionStates.ProjectionStateItem", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DesiredState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DesiredStateChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Position")
                        .HasColumnType("bigint");

                    b.HasKey("Name");

                    b.ToTable("ProjectionStates", "road");
                });

            modelBuilder.Entity("RoadRegistry.WmsWfsV2.Schema.Records.DerivedRoadSegmentRecord", b =>
                {
                    b.Property<int>("WS_TEMPID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WS_TEMPID"));

                    b.Property<int?>("B_WK_OIDN")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CREATIE")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EUNUMMERS")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("E_WK_OIDN")
                        .HasColumnType("int");

                    b.Property<Geometry>("GEOMETRIE")
                        .HasColumnType("Geometry");

                    b.Property<string>("LBEHEER")
                        .HasColumnType("varchar(18)");

                    b.Property<string>("LBLBEHEER")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("LBLLBEHEER")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LBLMETHODE")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LBLMORF")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LBLRBEHEER")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LBLSTATUS")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LBLTOEGANG")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LBLVERHARD")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LBLVERKEERSTYPE_AUTO")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LBLVERKEERSTYPE_FIETS")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LBLVERKEERSTYPE_VOETGANGER")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LBLWEGCAT")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LSTRNM")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("LSTRNMID")
                        .HasColumnType("int");

                    b.Property<int?>("METHODE")
                        .HasColumnType("int");

                    b.Property<int?>("MORF")
                        .HasColumnType("int");

                    b.Property<string>("NWNUMMERS")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RBEHEER")
                        .HasColumnType("varchar(18)");

                    b.Property<string>("RSTRNM")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("RSTRNMID")
                        .HasColumnType("int");

                    b.Property<int?>("STATUS")
                        .HasColumnType("int");

                    b.Property<string>("STRNM")
                        .HasColumnType("varchar(512)");

                    b.Property<int?>("TOEGANG")
                        .HasColumnType("int");

                    b.Property<int?>("VERHARDING")
                        .HasColumnType("int");

                    b.Property<int?>("VERKEERSTYPE_AUTO")
                        .HasColumnType("int");

                    b.Property<int?>("VERKEERSTYPE_FIETS")
                        .HasColumnType("int");

                    b.Property<int?>("VERKEERSTYPE_VOETGANGER")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("VERSIE")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WEGCAT")
                        .HasColumnType("varchar(5)");

                    b.Property<int>("WS_OIDN")
                        .HasColumnType("int");

                    b.HasKey("WS_TEMPID");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("WS_TEMPID"));

                    b.HasIndex("LBEHEER");

                    b.HasIndex("LBLBEHEER");

                    b.HasIndex("LBLMETHODE");

                    b.HasIndex("LBLMORF");

                    b.HasIndex("LBLSTATUS");

                    b.HasIndex("LBLTOEGANG");

                    b.HasIndex("LBLVERHARD");

                    b.HasIndex("LBLVERKEERSTYPE_AUTO");

                    b.HasIndex("LBLVERKEERSTYPE_FIETS");

                    b.HasIndex("LBLVERKEERSTYPE_VOETGANGER");

                    b.HasIndex("LBLWEGCAT");

                    b.HasIndex("LSTRNMID");

                    b.HasIndex("METHODE");

                    b.HasIndex("MORF");

                    b.HasIndex("RBEHEER");

                    b.HasIndex("RSTRNMID");

                    b.HasIndex("STATUS");

                    b.HasIndex("STRNM");

                    b.HasIndex("TOEGANG");

                    b.HasIndex("VERHARDING");

                    b.HasIndex("VERKEERSTYPE_AUTO");

                    b.HasIndex("VERKEERSTYPE_FIETS");

                    b.HasIndex("VERKEERSTYPE_VOETGANGER");

                    b.HasIndex("WEGCAT");

                    b.HasIndex("WS_OIDN");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("WS_OIDN"), false);

                    b.ToTable("AfgeleideWegsegmenten", "road");
                });

            modelBuilder.Entity("RoadRegistry.WmsWfsV2.Schema.Records.EuropeanRoadRecord", b =>
                {
                    b.Property<int>("EU_OIDN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EU_OIDN"));

                    b.Property<DateTimeOffset>("CREATIE")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EUNUMMER")
                        .HasColumnType("varchar(4)");

                    b.Property<DateTimeOffset>("VERSIE")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("WS_OIDN")
                        .HasColumnType("int");

                    b.HasKey("EU_OIDN");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("EU_OIDN"));

                    b.HasIndex("WS_OIDN");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("WS_OIDN"), false);

                    b.ToTable("EuropeseWegen", "road");
                });

            modelBuilder.Entity("RoadRegistry.WmsWfsV2.Schema.Records.GradeJunctionRecord", b =>
                {
                    b.Property<int>("GK_OIDN")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CREATIE")
                        .HasColumnType("datetimeoffset");

                    b.Property<Geometry>("GEOMETRIE")
                        .HasColumnType("Geometry");

                    b.Property<DateTimeOffset>("VERSIE")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("WS1_OIDN")
                        .HasColumnType("int");

                    b.Property<int>("WS2_OIDN")
                        .HasColumnType("int");

                    b.HasKey("GK_OIDN");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("GK_OIDN"));

                    b.HasIndex("WS1_OIDN");

                    b.HasIndex("WS2_OIDN");

                    b.ToTable("GelijkgrondseKruisingen", "road");
                });

            modelBuilder.Entity("RoadRegistry.WmsWfsV2.Schema.Records.GradeSeparatedJunctionRecord", b =>
                {
                    b.Property<int>("OK_OIDN")
                        .HasColumnType("int");

                    b.Property<int>("BO_WS_OIDN")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CREATIE")
                        .HasColumnType("datetimeoffset");

                    b.Property<Geometry>("GEOMETRIE")
                        .HasColumnType("Geometry");

                    b.Property<string>("LBLTYPE")
                        .HasColumnType("varchar(64)");

                    b.Property<int>("ON_WS_OIDN")
                        .HasColumnType("int");

                    b.Property<int?>("TYPE")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("VERSIE")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("OK_OIDN");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("OK_OIDN"));

                    b.HasIndex("BO_WS_OIDN");

                    b.HasIndex("ON_WS_OIDN");

                    b.ToTable("OngelijkgrondseKruisingen", "road");
                });

            modelBuilder.Entity("RoadRegistry.WmsWfsV2.Schema.Records.NationalRoadRecord", b =>
                {
                    b.Property<int>("NW_OIDN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NW_OIDN"));

                    b.Property<DateTimeOffset>("CREATIE")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NWNUMMER")
                        .HasColumnType("varchar(8)");

                    b.Property<DateTimeOffset>("VERSIE")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("WS_OIDN")
                        .HasColumnType("int");

                    b.HasKey("NW_OIDN");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("NW_OIDN"));

                    b.HasIndex("WS_OIDN");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("WS_OIDN"), false);

                    b.ToTable("NationaleWegen", "road");
                });

            modelBuilder.Entity("RoadRegistry.WmsWfsV2.Schema.Records.OrganizationCacheRecord", b =>
                {
                    b.Property<string>("OrganisatieId")
                        .HasColumnType("varchar(18)");

                    b.Property<bool>("IsWegbeheerder")
                        .HasColumnType("bit");

                    b.Property<string>("Naam")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("OvoCode")
                        .HasColumnType("varchar(9)");

                    b.HasKey("OrganisatieId");

                    b.ToTable("OrganisatieCache", "road");
                });

            modelBuilder.Entity("RoadRegistry.WmsWfsV2.Schema.Records.RoadNodeRecord", b =>
                {
                    b.Property<int>("WK_OIDN")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CREATIE")
                        .HasColumnType("datetimeoffset");

                    b.Property<Geometry>("GEOMETRIE")
                        .HasColumnType("Geometry");

                    b.Property<int?>("GRENSKNOOP")
                        .HasColumnType("int");

                    b.Property<string>("LBLTYPE")
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("TYPE")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("VERSIE")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("WK_OIDN");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("WK_OIDN"));

                    b.HasIndex("LBLTYPE");

                    b.ToTable("Wegknopen", "road");
                });

            modelBuilder.Entity("RoadRegistry.WmsWfsV2.Schema.Records.RoadSegmentRecord", b =>
                {
                    b.Property<int>("WS_OIDN")
                        .HasColumnType("int");

                    b.Property<int?>("B_WK_OIDN")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CREATIE")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DynamicAttributesJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DynamicAttributes");

                    b.Property<int?>("E_WK_OIDN")
                        .HasColumnType("int");

                    b.Property<Geometry>("GEOMETRIE")
                        .HasColumnType("Geometry");

                    b.Property<string>("LBLMETHODE")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LBLSTATUS")
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("METHODE")
                        .HasColumnType("int");

                    b.Property<int?>("STATUS")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("VERSIE")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("WS_OIDN");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("WS_OIDN"));

                    b.ToTable("Wegsegmenten", "road");
                });

            modelBuilder.Entity("RoadRegistry.WmsWfsV2.Schema.Records.StreetNameCacheRecord", b =>
                {
                    b.Property<int>("StraatnaamId")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .HasColumnType("varchar(255)");

                    b.HasKey("StraatnaamId");

                    b.ToTable("StraatnaamCache", "road");
                });
#pragma warning restore 612, 618
        }
    }
}
