// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using RoadRegistry.Pbs.Schema;

#nullable disable

namespace RoadRegistry.Pbs.Schema.Migrations
{
    [DbContext(typeof(PbsContext))]
    partial class PbsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Be.Vlaanderen.Basisregisters.ProjectionHandling.Runner.ProjectionStates.ProjectionStateItem", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DesiredState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DesiredStateChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Position")
                        .HasColumnType("bigint");

                    b.HasKey("Name");

                    b.ToTable("ProjectionStates", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.DerivedRoadSegmentRecord", b =>
                {
                    b.Property<int>("WS_TEMPID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WS_TEMPID"));

                    b.Property<int?>("AUTOHEEN")
                        .HasColumnType("int");

                    b.Property<int?>("AUTOTERUG")
                        .HasColumnType("int");

                    b.Property<int?>("B_WK_OIDN")
                        .HasColumnType("int");

                    b.Property<string>("CREATIE")
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("E_WK_OIDN")
                        .HasColumnType("int");

                    b.Property<int?>("FIETSHEEN")
                        .HasColumnType("int");

                    b.Property<int?>("FIETSTERUG")
                        .HasColumnType("int");

                    b.Property<Geometry>("GEOMETRIE")
                        .HasColumnType("Geometry");

                    b.Property<string>("LBEHEER")
                        .HasColumnType("varchar(18)");

                    b.Property<string>("LBLMETHODE")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LBLMORF")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LBLSTATUS")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LBLTOEGANG")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LBLVERHARD")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LBLWEGCAT")
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("LSTRNMID")
                        .HasColumnType("int");

                    b.Property<int?>("METHODE")
                        .HasColumnType("int");

                    b.Property<int?>("MORF")
                        .HasColumnType("int");

                    b.Property<string>("RBEHEER")
                        .HasColumnType("varchar(18)");

                    b.Property<int?>("RSTRNMID")
                        .HasColumnType("int");

                    b.Property<int?>("STATUS")
                        .HasColumnType("int");

                    b.Property<int?>("TOEGANG")
                        .HasColumnType("int");

                    b.Property<int?>("VERHARDING")
                        .HasColumnType("int");

                    b.Property<string>("VERSIE")
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("VOETGANGER")
                        .HasColumnType("int");

                    b.Property<string>("WEGCAT")
                        .HasColumnType("varchar(5)");

                    b.Property<int>("WS_OIDN")
                        .HasColumnType("int");

                    b.HasKey("WS_TEMPID");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("WS_TEMPID"));

                    b.HasIndex("WS_OIDN");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("WS_OIDN"), false);

                    b.ToTable("AfgeleideWegsegmenten", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.EuropeanRoadRecord", b =>
                {
                    b.Property<int>("EU_OIDN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EU_OIDN"));

                    b.Property<string>("CREATIE")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("EUNUMMER")
                        .HasColumnType("varchar(4)");

                    b.Property<string>("VERSIE")
                        .HasColumnType("varchar(15)");

                    b.Property<int>("WS_OIDN")
                        .HasColumnType("int");

                    b.HasKey("EU_OIDN");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("EU_OIDN"));

                    b.HasIndex("WS_OIDN");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("WS_OIDN"), false);

                    b.ToTable("EuropeseWegen", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.GradeJunctionRecord", b =>
                {
                    b.Property<int>("GK_OIDN")
                        .HasColumnType("int");

                    b.Property<string>("CREATIE")
                        .HasColumnType("varchar(15)");

                    b.Property<Geometry>("GEOMETRIE")
                        .HasColumnType("Geometry");

                    b.Property<string>("VERSIE")
                        .HasColumnType("varchar(15)");

                    b.Property<int>("WS1_OIDN")
                        .HasColumnType("int");

                    b.Property<int>("WS2_OIDN")
                        .HasColumnType("int");

                    b.HasKey("GK_OIDN");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("GK_OIDN"));

                    b.HasIndex("WS1_OIDN");

                    b.HasIndex("WS2_OIDN");

                    b.ToTable("GelijkgrondseKruisingen", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.GradeSeparatedJunctionRecord", b =>
                {
                    b.Property<int>("OK_OIDN")
                        .HasColumnType("int");

                    b.Property<int>("BO_WS_OIDN")
                        .HasColumnType("int");

                    b.Property<string>("CREATIE")
                        .HasColumnType("varchar(15)");

                    b.Property<Geometry>("GEOMETRIE")
                        .HasColumnType("Geometry");

                    b.Property<string>("LBLTYPE")
                        .HasColumnType("varchar(64)");

                    b.Property<int>("ON_WS_OIDN")
                        .HasColumnType("int");

                    b.Property<int?>("TYPE")
                        .HasColumnType("int");

                    b.Property<string>("VERSIE")
                        .HasColumnType("varchar(15)");

                    b.HasKey("OK_OIDN");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("OK_OIDN"));

                    b.HasIndex("BO_WS_OIDN");

                    b.HasIndex("ON_WS_OIDN");

                    b.ToTable("OngelijkgrondseKruisingen", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.GradeSeparatedJunctionTypeCodeListRecord", b =>
                {
                    b.Property<int>("TYPE")
                        .HasColumnType("int");

                    b.Property<string>("DEFTYPE")
                        .HasColumnType("varchar(254)");

                    b.Property<string>("LBLTYPE")
                        .HasColumnType("varchar(64)");

                    b.HasKey("TYPE");

                    b.ToTable("OngelijkgrondseKruisingCodelijstType", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.NationalRoadRecord", b =>
                {
                    b.Property<int>("NW_OIDN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NW_OIDN"));

                    b.Property<string>("CREATIE")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("NWNUMMER")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("VERSIE")
                        .HasColumnType("varchar(15)");

                    b.Property<int>("WS_OIDN")
                        .HasColumnType("int");

                    b.HasKey("NW_OIDN");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("NW_OIDN"));

                    b.HasIndex("WS_OIDN");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("WS_OIDN"), false);

                    b.ToTable("NationaleWegen", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.OrganizationCacheRecord", b =>
                {
                    b.Property<string>("OrganisatieId")
                        .HasColumnType("varchar(18)");

                    b.Property<bool>("IsWegbeheerder")
                        .HasColumnType("bit");

                    b.Property<string>("Naam")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("OvoCode")
                        .HasColumnType("varchar(9)");

                    b.HasKey("OrganisatieId");

                    b.ToTable("OrganisatieCache", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.RoadNodeRecord", b =>
                {
                    b.Property<int>("WK_OIDN")
                        .HasColumnType("int");

                    b.Property<string>("CREATIE")
                        .HasColumnType("varchar(15)");

                    b.Property<Geometry>("GEOMETRIE")
                        .HasColumnType("Geometry");

                    b.Property<int?>("GRENSKNOOP")
                        .HasColumnType("int");

                    b.Property<string>("LBLTYPE")
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("TYPE")
                        .HasColumnType("int");

                    b.Property<string>("VERSIE")
                        .HasColumnType("varchar(15)");

                    b.HasKey("WK_OIDN");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("WK_OIDN"));

                    b.ToTable("Wegknopen", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.RoadNodeTypeCodeListRecord", b =>
                {
                    b.Property<int>("TYPE")
                        .HasColumnType("int");

                    b.Property<string>("DEFTYPE")
                        .HasColumnType("varchar(254)");

                    b.Property<string>("LBLTYPE")
                        .HasColumnType("varchar(64)");

                    b.HasKey("TYPE");

                    b.ToTable("WegknoopCodelijstType", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.RoadSegmentAccessRestrictionAttributeRecord", b =>
                {
                    b.Property<int>("TO_OIDN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TO_OIDN"));

                    b.Property<string>("LBLTOEGANG")
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("TOEGANG")
                        .HasColumnType("int");

                    b.Property<double>("TOTPOS")
                        .HasColumnType("float");

                    b.Property<double>("VANPOS")
                        .HasColumnType("float");

                    b.Property<int>("WS_OIDN")
                        .HasColumnType("int");

                    b.HasKey("TO_OIDN");

                    b.HasIndex("WS_OIDN");

                    b.ToTable("WegsegmentToegangAttributen", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.RoadSegmentAccessRestrictionCodeListRecord", b =>
                {
                    b.Property<int>("TOEGANG")
                        .HasColumnType("int");

                    b.Property<string>("DEFTOEGANG")
                        .HasColumnType("varchar(254)");

                    b.Property<string>("LBLTOEGANG")
                        .HasColumnType("varchar(64)");

                    b.HasKey("TOEGANG");

                    b.ToTable("WegsegmentCodelijstToegang", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.RoadSegmentBikeTrafficDirectionAttributeRecord", b =>
                {
                    b.Property<int>("FI_OIDN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FI_OIDN"));

                    b.Property<string>("LBLRICHT")
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("RICHTING")
                        .HasColumnType("int");

                    b.Property<double>("TOTPOS")
                        .HasColumnType("float");

                    b.Property<double>("VANPOS")
                        .HasColumnType("float");

                    b.Property<int>("WS_OIDN")
                        .HasColumnType("int");

                    b.HasKey("FI_OIDN");

                    b.HasIndex("WS_OIDN");

                    b.ToTable("WegsegmentVerkeerstypeFietsAttributen", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.RoadSegmentCarTrafficDirectionAttributeRecord", b =>
                {
                    b.Property<int>("AU_OIDN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AU_OIDN"));

                    b.Property<string>("LBLRICHT")
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("RICHTING")
                        .HasColumnType("int");

                    b.Property<double>("TOTPOS")
                        .HasColumnType("float");

                    b.Property<double>("VANPOS")
                        .HasColumnType("float");

                    b.Property<int>("WS_OIDN")
                        .HasColumnType("int");

                    b.HasKey("AU_OIDN");

                    b.HasIndex("WS_OIDN");

                    b.ToTable("WegsegmentVerkeerstypeAutoAttributen", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.RoadSegmentCategoryAttributeRecord", b =>
                {
                    b.Property<int>("WC_OIDN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WC_OIDN"));

                    b.Property<string>("LBLWEGCAT")
                        .HasColumnType("varchar(64)");

                    b.Property<double>("TOTPOS")
                        .HasColumnType("float");

                    b.Property<double>("VANPOS")
                        .HasColumnType("float");

                    b.Property<string>("WEGCAT")
                        .HasColumnType("varchar(5)");

                    b.Property<int>("WS_OIDN")
                        .HasColumnType("int");

                    b.HasKey("WC_OIDN");

                    b.HasIndex("WS_OIDN");

                    b.ToTable("WegsegmentWegcategorieAttributen", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.RoadSegmentCategoryCodeListRecord", b =>
                {
                    b.Property<string>("WEGCAT")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("DEFWEGCAT")
                        .HasColumnType("varchar(254)");

                    b.Property<string>("LBLWEGCAT")
                        .HasColumnType("varchar(64)");

                    b.HasKey("WEGCAT");

                    b.ToTable("WegsegmentCodelijstWegcategorie", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.RoadSegmentDirectionCodeListRecord", b =>
                {
                    b.Property<int>("RICHTING")
                        .HasColumnType("int");

                    b.Property<string>("DEFRICHT")
                        .HasColumnType("varchar(254)");

                    b.Property<string>("LBLRICHT")
                        .HasColumnType("varchar(64)");

                    b.HasKey("RICHTING");

                    b.ToTable("WegsegmentCodelijstRichting", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.RoadSegmentMaintenanceAuthorityAttributeRecord", b =>
                {
                    b.Property<int>("WB_OIDN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WB_OIDN"));

                    b.Property<string>("BEHEER")
                        .HasColumnType("varchar(18)");

                    b.Property<int?>("KANT")
                        .HasColumnType("int");

                    b.Property<string>("LBLKANT")
                        .HasColumnType("varchar(64)");

                    b.Property<double>("TOTPOS")
                        .HasColumnType("float");

                    b.Property<double>("VANPOS")
                        .HasColumnType("float");

                    b.Property<int>("WS_OIDN")
                        .HasColumnType("int");

                    b.HasKey("WB_OIDN");

                    b.HasIndex("WS_OIDN");

                    b.ToTable("WegsegmentWegbeheerderAttributen", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.RoadSegmentMaintenanceAuthorityCodeListRecord", b =>
                {
                    b.Property<string>("BEHEER")
                        .HasColumnType("varchar(18)");

                    b.Property<string>("LBLBEHEER")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("OVOCODE")
                        .HasColumnType("varchar(9)");

                    b.HasKey("BEHEER");

                    b.ToTable("WegsegmentCodelijstWegbeheerder", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.RoadSegmentMethodCodeListRecord", b =>
                {
                    b.Property<int>("METHODE")
                        .HasColumnType("int");

                    b.Property<string>("DEFMETHODE")
                        .HasColumnType("varchar(254)");

                    b.Property<string>("LBLMETHODE")
                        .HasColumnType("varchar(64)");

                    b.HasKey("METHODE");

                    b.ToTable("WegsegmentCodelijstMethode", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.RoadSegmentMorphologyAttributeRecord", b =>
                {
                    b.Property<int>("MO_OIDN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MO_OIDN"));

                    b.Property<string>("LBLMORF")
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("MORF")
                        .HasColumnType("int");

                    b.Property<double>("TOTPOS")
                        .HasColumnType("float");

                    b.Property<double>("VANPOS")
                        .HasColumnType("float");

                    b.Property<int>("WS_OIDN")
                        .HasColumnType("int");

                    b.HasKey("MO_OIDN");

                    b.HasIndex("WS_OIDN");

                    b.ToTable("WegsegmentMorfologieAttributen", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.RoadSegmentMorphologyCodeListRecord", b =>
                {
                    b.Property<int>("MORF")
                        .HasColumnType("int");

                    b.Property<string>("DEFMORF")
                        .HasColumnType("varchar(254)");

                    b.Property<string>("LBLMORF")
                        .HasColumnType("varchar(64)");

                    b.HasKey("MORF");

                    b.ToTable("WegsegmentCodelijstMorfologie", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.RoadSegmentPedestrianTrafficDirectionAttributeRecord", b =>
                {
                    b.Property<int>("VO_OIDN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VO_OIDN"));

                    b.Property<string>("LBLRICHT")
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("RICHTING")
                        .HasColumnType("int");

                    b.Property<double>("TOTPOS")
                        .HasColumnType("float");

                    b.Property<double>("VANPOS")
                        .HasColumnType("float");

                    b.Property<int>("WS_OIDN")
                        .HasColumnType("int");

                    b.HasKey("VO_OIDN");

                    b.HasIndex("WS_OIDN");

                    b.ToTable("WegsegmentVerkeerstypeVoetgangerAttributen", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.RoadSegmentRecord", b =>
                {
                    b.Property<int>("WS_OIDN")
                        .HasColumnType("int");

                    b.Property<int?>("B_WK_OIDN")
                        .HasColumnType("int");

                    b.Property<string>("CREATIE")
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("E_WK_OIDN")
                        .HasColumnType("int");

                    b.Property<Geometry>("GEOMETRIE")
                        .HasColumnType("Geometry");

                    b.Property<string>("LBLMETHODE")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LBLSTATUS")
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("METHODE")
                        .HasColumnType("int");

                    b.Property<int?>("STATUS")
                        .HasColumnType("int");

                    b.Property<string>("VERSIE")
                        .HasColumnType("varchar(15)");

                    b.HasKey("WS_OIDN");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("WS_OIDN"));

                    b.ToTable("Wegsegmenten", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.RoadSegmentSideCodeListRecord", b =>
                {
                    b.Property<int>("KANT")
                        .HasColumnType("int");

                    b.Property<string>("DEFKANT")
                        .HasColumnType("varchar(254)");

                    b.Property<string>("LBLKANT")
                        .HasColumnType("varchar(64)");

                    b.HasKey("KANT");

                    b.ToTable("WegsegmentCodelijstKant", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.RoadSegmentStatusCodeListRecord", b =>
                {
                    b.Property<int>("STATUS")
                        .HasColumnType("int");

                    b.Property<string>("DEFSTATUS")
                        .HasColumnType("varchar(254)");

                    b.Property<string>("LBLSTATUS")
                        .HasColumnType("varchar(64)");

                    b.HasKey("STATUS");

                    b.ToTable("WegsegmentCodelijstStatus", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.RoadSegmentStreetNameAttributeRecord", b =>
                {
                    b.Property<int>("SN_OIDN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SN_OIDN"));

                    b.Property<int?>("KANT")
                        .HasColumnType("int");

                    b.Property<string>("LBLKANT")
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("STRTNMID")
                        .HasColumnType("int");

                    b.Property<double>("TOTPOS")
                        .HasColumnType("float");

                    b.Property<double>("VANPOS")
                        .HasColumnType("float");

                    b.Property<int>("WS_OIDN")
                        .HasColumnType("int");

                    b.HasKey("SN_OIDN");

                    b.HasIndex("WS_OIDN");

                    b.ToTable("WegsegmentStraatnaamAttributen", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.RoadSegmentSurfaceTypeAttributeRecord", b =>
                {
                    b.Property<int>("WV_OIDN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WV_OIDN"));

                    b.Property<string>("LBLVERHARD")
                        .HasColumnType("varchar(64)");

                    b.Property<double>("TOTPOS")
                        .HasColumnType("float");

                    b.Property<double>("VANPOS")
                        .HasColumnType("float");

                    b.Property<int?>("VERHARDING")
                        .HasColumnType("int");

                    b.Property<int>("WS_OIDN")
                        .HasColumnType("int");

                    b.HasKey("WV_OIDN");

                    b.HasIndex("WS_OIDN");

                    b.ToTable("WegsegmentWegverhardingAttributen", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.RoadSegmentSurfaceTypeCodeListRecord", b =>
                {
                    b.Property<int>("VERHARDING")
                        .HasColumnType("int");

                    b.Property<string>("DEFVERHARD")
                        .HasColumnType("varchar(254)");

                    b.Property<string>("LBLVERHARD")
                        .HasColumnType("varchar(64)");

                    b.HasKey("VERHARDING");

                    b.ToTable("WegsegmentCodelijstVerharding", "RoadRegistryPbs");
                });

            modelBuilder.Entity("RoadRegistry.Pbs.Schema.Records.StreetNameCacheRecord", b =>
                {
                    b.Property<int>("StraatnaamId")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .HasColumnType("varchar(255)");

                    b.HasKey("StraatnaamId");

                    b.ToTable("StraatnaamCache", "RoadRegistryPbs");
                });
#pragma warning restore 612, 618
        }
    }
}
