namespace RoadRegistry.Infrastructure.MartenDb.Projections;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using BackOffice;
using Marten;

// The projection state of a Marten async projection: what an operator wants the shard to be doing. It is the same
// thing the stream-store projections have always kept on their ProjectionStates row - "subscribed" or "stopped" -
// which is why the status page's start/stop control means "should be running" rather than "is running".
//
// The Marten projections had no such row, so nothing survived a restart: the daemon starts every shard on boot and the
// supervisor resumed everything that was not running, which undid a deliberate stop within minutes. What the shard is
// actually doing is not stored here - that is asked of the daemon, which always knows.
//
// It lives here rather than with the Projector that uses it because Marten runs with AutoCreate.None: the schema comes
// from the migrations, which are generated by diffing against MigrationModel.ConfigureAllRoadDocuments. A document type
// the generator's model cannot see is a table that never gets created.
public sealed class MartenProjectionState
{
    // The shard name, e.g. "RoadNetworkChangesReadProjection:All".
    public required string Id { get; set; }
    public required string DesiredState { get; set; }
    public DateTimeOffset DesiredStateChangedAt { get; set; }
}

// The vocabulary the projections status page already speaks for the stream-store projections; the Marten ones use the
// same words so the page needs no special case.
public static class ProjectionDesiredStates
{
    public const string Subscribed = "subscribed";
    public const string Stopped = "stopped";
}

public sealed class MartenProjectionStateStore
{
    private readonly IDocumentStore _documentStore;

    public MartenProjectionStateStore(IDocumentStore documentStore)
    {
        _documentStore = documentStore;
    }

    // One query for every shard: both readers (the daemon starting up and the supervisor's tick) want them all.
    public async Task<Dictionary<string, string>> GetDesiredStatesAsync(CancellationToken cancellationToken)
    {
        await using var session = _documentStore.QuerySession();
        var states = await session.Query<MartenProjectionState>().ToListAsync(cancellationToken);
        return states.ToDictionary(x => x.Id, x => x.DesiredState);
    }

    public async Task SetDesiredStateAsync(string shardName, string desiredState, CancellationToken cancellationToken)
    {
        await using var session = _documentStore.LightweightSession();
        session.Store(new MartenProjectionState
        {
            Id = shardName,
            DesiredState = desiredState,
            DesiredStateChangedAt = DateTimeOffset.UtcNow
        });
        await session.SaveChangesAsync(cancellationToken);
    }
}

public static class MartenProjectionStateExtensions
{
    public static StoreOptions ConfigureMartenProjectionState(this StoreOptions options)
    {
        options.Schema.For<MartenProjectionState>()
            .DatabaseSchemaName(WellKnownSchemas.MartenEventStore)
            .DocumentAlias("martenprojection_state")
            .Identity(x => x.Id);

        return options;
    }
}
