version: '3.8'

services:

  backoffice-api:
    build: ../../dist/RoadRegistry.BackOffice.Api/linux
    container_name: backoffice-api
    extends:
      file: base.yml
      service: aspnetcore-backoffice-host
    ports:
      - 5020:10002
    environment:
      S3BLOBCLIENTOPTIONS__BUCKETS__EXTRACTDOWNLOADS: road-registry-extract-downloads
      CONNECTIONSTRINGS__EDITORPROJECTIONS: Data Source=tcp:mssql,1433;Initial Catalog=road-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CONNECTIONSTRINGS__PRODUCTPROJECTIONS: Data Source=tcp:mssql,1433;Initial Catalog=road-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CONNECTIONSTRINGS__SYNDICATIONPROJECTIONS: Data Source=tcp:mssql,1433;Initial Catalog=road-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      IDEMPOTENCY__CONNECTIONSTRING: Data Source=tcp:mssql,1433;Initial Catalog=road-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CORS__0: http://localhost:5010
      CORS__1: http://localhost:1234

  backoffice-event-host:
    build: ../../dist/RoadRegistry.BackOffice.EventHost/linux
    container_name: backoffice-event-host
    extends:
      file: base.yml
      service: dotnet-backoffice-host
    environment:
      CONNECTIONSTRINGS__EVENTHOST: Data Source=tcp:mssql,1433;Initial Catalog=road-registry-events;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CONNECTIONSTRINGS__EVENTHOSTADMIN: Data Source=tcp:mssql,1433;Initial Catalog=road-registry-events;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True

  backoffice-extract-host:
    build: ../../dist/RoadRegistry.BackOffice.ExtractHost/linux
    container_name: backoffice-extract-host
    extends:
      file: base.yml
      service: dotnet-backoffice-host
    environment:
      S3BLOBCLIENTOPTIONS__BUCKETS__EXTRACTDOWNLOADS: road-registry-extract-downloads
      CONNECTIONSTRINGS__EXTRACTHOST: Data Source=tcp:mssql,1433;Initial Catalog=road-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CONNECTIONSTRINGS__EXTRACTHOSTADMIN: Data Source=tcp:mssql,1433;Initial Catalog=road-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CONNECTIONSTRINGS__EDITORPROJECTIONS: Data Source=tcp:mssql,1433;Initial Catalog=road-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CONNECTIONSTRINGS__SYNDICATIONPROJECTIONS: Data Source=tcp:mssql,1433;Initial Catalog=road-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True

  backoffice-command-host:
    build: ../../dist/RoadRegistry.BackOffice.CommandHost/linux
    container_name: backoffice-command-host
    extends:
      file: base.yml
      service: dotnet-backoffice-host
    environment:
      CONNECTIONSTRINGS__COMMANDHOST: Data Source=tcp:mssql,1433;Initial Catalog=road-registry-events;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CONNECTIONSTRINGS__COMMANDHOSTADMIN: Data Source=tcp:mssql,1433;Initial Catalog=road-registry-events;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True

  backoffice-messaging-host-sqs:
    build: ../../dist/RoadRegistry.BackOffice.MessagingHost.Sqs/linux
    container_name: backoffice-messaging-host-sqs
    extends:
      file: base.yml
      service: dotnet-backoffice-host
    environment:
      S3BLOBCLIENTOPTIONS__BUCKETS__FEATURECOMPARE: road-registry-feature-compare
      FEATURECOMPAREMESSAGINGOPTIONS__REQUESTQUEUEURL: https://sqs.eu-west-1.amazonaws.com/830031229216/sqs-road-registry-feature-compare-request.fifo
      FEATURECOMPAREMESSAGINGOPTIONS__RESPONSEQUEUEURL: https://sqs.eu-west-1.amazonaws.com/830031229216/sqs-road-registry-feature-compare-response.fifo
      FEATURECOMPAREMESSAGINGOPTIONS__CONSUMERDELAYSECONDS: 30

  backoffice-ui:
    build: 
      context: ../../dist/RoadRegistry.BackOffice.UI/linux
      args:
        build_number: 2.38.0
    container_name: backoffice-ui
    depends_on:
      - backoffice-api
    ports:
      - 5010:10007
    environment:
      API_ENDPOINT: http://localhost:2080
      API_OLDENDPOINT: http://localhost:5020
    profiles:
      - ui

networks:
  default:
    name: road-registry-network
    external: true
