version: '3.8'

services:

  base-service:
    environment:
      SERILOG__WRITETO__0__NAME: Seq
      SERILOG__WRITETO__0__ARGS__SERVERURL: http://localhost:5341
      SERILOG__WRITETO__1__NAME: Console
      SERILOG__MINIMUMLEVEL__OVERRIDE__ROADREGISTRY: Debug

  base-blob-service:
    environment:
      BLOBCLIENTTYPE: S3BlobClient
      S3__SERVICEURL: http://localhost:4566

  dotnet-service:
    extends:
      service: base-service
    environment:
      DOTNET_ENVIRONMENT: Development

  dotnet-blob-service:
    extends:
      service: dotnet-service
    environment:
      BLOBCLIENTTYPE: S3BlobClient
      S3__SERVICEURL: http://localhost:4566

  dotnet-backoffice-host:
    extends:
      service: dotnet-blob-service
    environment:
      S3BLOBCLIENTOPTIONS__BUCKETS__UPLOADS: road-registry-uploads
      CONNECTIONSTRINGS__SNAPSHOTS: Data Source=tcp:mssql,1433;Initial Catalog=road-registry-events;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CONNECTIONSTRINGS__SNAPSHOTSADMIN: Data Source=tcp:mssql,1433;Initial Catalog=road-registry-events;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CONNECTIONSTRINGS__EVENTS: Data Source=tcp:mssql,1433;Initial Catalog=road-registry-events;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True

  aspnetcore-backoffice-host:
    extends:
      service: aspnetcore-blob-service
    environment:
      S3BLOBCLIENTOPTIONS__BUCKETS__UPLOADS: road-registry-uploads
      CONNECTIONSTRINGS__SNAPSHOTS: Data Source=tcp:mssql,1433;Initial Catalog=road-registry-events;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CONNECTIONSTRINGS__SNAPSHOTSADMIN: Data Source=tcp:mssql,1433;Initial Catalog=road-registry-events;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CONNECTIONSTRINGS__EVENTS: Data Source=tcp:mssql,1433;Initial Catalog=road-registry-events;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True

  aspnetcore-service:
    extends:
      service: base-service
    environment:
      ASPNETCORE__ENVIRONMENT: Development
      DATADOG__ENABLED: false
      DATADOG__DEBUG: false

  aspnetcore-blob-service:
    extends:
      service: aspnetcore-service
    environment:
      BLOBCLIENTTYPE: S3BlobClient
      S3__SERVICEURL: http://localhost:4566

  lambda-host:
    extends:
      service: dotnet-blob-service
    environment:
      FEATURETOGGLES__USESNAPSHOTSQSREQUEST: true
      TICKETINGSERVICE__INTERNALBASEURL: http://ticketing-service:9100/ticketing
      TICKETINGSERVICE__PUBLICBASEURL: http://ticketing-service:9100/tickets
      S3BLOBCLIENTOPTIONS__BUCKETS__SNAPSHOTS: road-registry-snapshots
      S3BLOBCLIENTOPTIONS__BUCKETS__SQSMESSAGES: road-registry-sqs-messages
      DISTRIBUTEDS3CACHEOPTIONS__BUCKET: road-registry-snapshots
      DISTRIBUTEDS3CACHEOPTIONS__ROOTDIR: snapshots
      DISTRIBUTEDSTREAMSTORELOCK__ENABLED: true
      CONNECTIONSTRINGS__EVENTS: Data Source=tcp:mssql,1433;Initial Catalog=road-registry-events;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CONNECTIONSTRINGS__SNAPSHOTS: Data Source=tcp:mssql,1433;Initial Catalog=road-registry-events;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True

  projection-host:
    extends:
      service: dotnet-service
    environment:
      CONNECTIONSTRINGS__EVENTS: Data Source=tcp:mssql,1433;Initial Catalog=road-registry-events;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True

  projection-blob-host:
    extends:
      service: projection-host
    environment:
      BLOBCLIENTTYPE: S3BlobClient
      S3__SERVICEURL: http://localstack:4566

  projection-scheduled-host:
    extends:
      service: projection-host
    environment:
      CONNECTIONSTRINGS__SYNDICATIONPROJECTIONS: Data Source=tcp:mssql,1433;Initial Catalog=road-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      METADATA__URI: http://wiremock:8080/metadatacenter/srv/dut/csw-publication
      METADATA__LOGINURI: http://wiremock:8080/metadatacenter/srv/dut/info?info=me

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: E@syP@ssw0rd
      MSSQL_MEMORY_LIMIT_MB: 1000
      MSSQL_PID: Standard

networks:
  default:
    name: road-registry-network
    external: true
    
