version: '3.8'

services:

  lambda-backoffice:
    build: ../../dist/RoadRegistry.Snapshot.Handlers.Sqs.Lambda/linux
    container_name: lambda-backoffice
    extends:
      file: base.yml
      service: lambda-host
    environment:
      CONNECTIONSTRINGS__EDITORPROJECTIONS: Data Source=tcp:mssql,1433;Initial Catalog=road-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CONNECTIONSTRINGS__SYNDICATIONPROJECTIONS: Data Source=tcp:mssql,1433;Initial Catalog=road-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True

  lambda-snapshots:
    build: ../../dist/RoadRegistry.BackOffice.Handlers.Sqs.Lambda/linux
    container_name: lambda-snapshots
    extends:
      file: base.yml
      service: lambda-host
    environment:
      SNAPSHOTOPTIONS__EVENTCOUNT: 3

networks:
  default:
    name: road-registry-network
    external: true
