version: '3.8'

services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: road-mssql
    extends:
      file: base.yml
      service: mssql
    ports:
      - 21433:1433
    volumes:
      - road-mssql-data:/var/opt/mssql
      - ../../src/RoadRegistry.BackupDatabase/filled:/var/lib/backup

  mssql-seed:
    build: ../../src/RoadRegistry.Database
    container_name: road-mssql-seed
    depends_on:
      - mssql
    profiles:
      - seed

  import-backup:
    build: ../../src/RoadRegistry.BackupDatabase/filled
    container_name: road-mssql-import-backup
    depends_on:
      - mssql-seed
    volumes:
      - ../../src/RoadRegistry.BackupDatabase/filled:/var/lib/backup
    profiles:
      - seed

  import-legacy:
    build: ../../dist/RoadRegistry.Legacy.Import/linux
    container_name: import-legacy
    extends:
      file: base.yml
      service: dotnet-blob-service
    environment:
      S3BLOBCLIENTOPTIONS__BUCKETS__IMPORTLEGACY: road-registry-import-legacy
      CONNECTIONSTRINGS__EVENTS: Data Source=tcp:mssql,1433;Initial Catalog=road-registry-events;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
    volumes:
      - ../../src/RoadRegistry.Legacy.Extract:/var/lib/RoadRegistry.Legacy.Extract
    profiles:
      - seed

volumes:
  road-mssql-data:
    name: road-mssql-data
    external: true

networks:
  default:
    name: road-registry-network
    external: true 
