version: '3.8'

services:

  municipality-api:
    image: 830031229216.dkr.ecr.eu-west-1.amazonaws.com/municipality-registry/api-legacy:4.1.11
    container_name: municipality-api
    extends:
      file: base.yml
      service: aspnetcore-service
    depends_on:
      - municipality-mssql
    ports:
      - 2002:2002
    environment:
      DATADOG__SERVICENAME: Municipalities-RoadRegistry
      CONNECTIONSTRINGS__EVENTS: Data Source=tcp:municipality-mssql,1433;Initial Catalog=municipality-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CONNECTIONSTRINGS__LEGACYPROJECTIONS: Data Source=tcp:municipality-mssql,1433;Initial Catalog=municipality-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CONNECTIONSTRINGS__LEGACYPROJECTIONSADMIN: Data Source=tcp:municipality-mssql,1433;Initial Catalog=municipality-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True

  municipality-mssql:
    container_name: municipality-mssql
    extends:
      file: base.yml
      service: mssql
    ports:
      - 41433:1433
    volumes:
      - municipality-mssql-data:/var/opt/mssql
      - ../../src/RoadRegistry.MunicipalityDatabase/filled:/var/lib/backup/filled

  municipality-mssql-seed-filled:
    build: ../../src/RoadRegistry.MunicipalityDatabase/filled
    container_name: municipality-mssql-seed-filled
    depends_on:
      - municipality-mssql
    volumes:
      - ../../src/RoadRegistry.MunicipalityDatabase/filled:/var/lib/backup
    profiles:
      - seed

volumes:
  municipality-mssql-data:
    name: municipality-mssql-data
    external: true

networks:
  default:
    name: road-registry-network
    external: true
