version: '3.8'

services:

  editor-projection-host:
    build: ../../dist/RoadRegistry.Editor.ProjectionHost/linux
    container_name: editor-projection-host
    extends: 
      file: base.yml
      service: projection-blob-host
    environment:
      S3BLOBCLIENTOPTIONS__BUCKETS__UPLOADS: road-registry-uploads
      CONNECTIONSTRINGS__EDITORPROJECTIONS: Data Source=tcp:mssql,1433;Initial Catalog=road-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CONNECTIONSTRINGS__EDITORPROJECTIONSADMIN: Data Source=tcp:mssql,1433;Initial Catalog=road-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True

  product-projection-host:
    build: ../../dist/RoadRegistry.Product.ProjectionHost/linux
    container_name: product-projection-host
    extends: 
      file: base.yml
      service: projection-host
    environment:
      CONNECTIONSTRINGS__PRODUCTPROJECTIONS: Data Source=tcp:mssql,1433;Initial Catalog=road-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CONNECTIONSTRINGS__PRODUCTPROJECTIONSADMIN: Data Source=tcp:mssql,1433;Initial Catalog=road-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True

  syndication-projection-host:
    build: ../../dist/RoadRegistry.Syndication.ProjectionHost/linux
    container_name: syndication-projection-host
    extends: 
      file: base.yml
      service: projection-host
    environment:
      MUNICIPALITYFEED__URI: http://municipality-api:2002/v1/gemeenten/sync
      STREETNAMEFEED__URI: http://streetname-api:4002/v1/straatnamen/sync
      CONNECTIONSTRINGS__SYNDICATIONPROJECTIONS: Data Source=tcp:mssql,1433;Initial Catalog=road-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CONNECTIONSTRINGS__SYNDICATIONPROJECTIONSADMIN: Data Source=tcp:mssql,1433;Initial Catalog=road-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True

  wfs-projection-host:
    build: ../../dist/RoadRegistry.Wfs.ProjectionHost/linux
    container_name: wfs-projection-host
    extends: 
      file: base.yml
      service: projection-scheduled-host
    environment:
      CONNECTIONSTRINGS__WFSPROJECTIONS: Data Source=tcp:mssql,1433;Initial Catalog=road-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CONNECTIONSTRINGS__WFSPROJECTIONSADMIN: Data Source=tcp:mssql,1433;Initial Catalog=road-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True

  wms-projection-host:
    build: ../../dist/RoadRegistry.Wms.ProjectionHost/linux
    container_name: wms-projection-host
    extends: 
      file: base.yml
      service: projection-scheduled-host
    environment:
      CONNECTIONSTRINGS__WMSPROJECTIONS: Data Source=tcp:mssql,1433;Initial Catalog=road-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CONNECTIONSTRINGS__WMSPROJECTIONSADMIN: Data Source=tcp:mssql,1433;Initial Catalog=road-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True

networks:
  default:
    name: road-registry-network
    external: true
