version: '3.8'

services:

  streetname-api:
    image: 830031229216.dkr.ecr.eu-west-1.amazonaws.com/streetname-registry/api-legacy:3.10.44
    container_name: streetname-api
    extends:
      file: base.yml
      service: aspnetcore-service
    depends_on:
      - streetname-mssql
    ports:
      - 4002:4002
    environment:
      DATADOG__SERVICENAME: Streetnames-RoadRegistry
      CONNECTIONSTRINGS__EVENTS: Data Source=tcp:streetname-mssql,1433;Initial Catalog=streetname-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CONNECTIONSTRINGS__LEGACYPROJECTIONS: Data Source=tcp:streetname-mssql,1433;Initial Catalog=streetname-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CONNECTIONSTRINGS__LEGACYPROJECTIONSADMIN: Data Source=tcp:streetname-mssql,1433;Initial Catalog=streetname-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True
      CONNECTIONSTRINGS__SYNDICATIONPROJECTIONS: Data Source=tcp:streetname-mssql,1433;Initial Catalog=streetname-registry;Integrated Security=False;User ID=sa;Password=E@syP@ssw0rd;TrustServerCertificate=True

  streetname-mssql:
    container_name: streetname-mssql
    extends:
      file: base.yml
      service: mssql
    ports:
      - 51433:1433
    volumes:
      - streetname-mssql-data:/var/opt/mssql
      - ../../src/RoadRegistry.StreetNameDatabase/filled:/var/lib/backup/filled

  streetname-mssql-seed-filled:
    build: ../../src/RoadRegistry.StreetNameDatabase/filled
    container_name: streetname-mssql-seed-filled
    depends_on:
      - streetname-mssql
    volumes:
      - ../../src/RoadRegistry.StreetNameDatabase/filled:/var/lib/backup
    profiles:
      - seed

volumes:
  streetname-mssql-data:
    name: streetname-mssql-data
    external: true

networks:
  default:
    name: road-registry-network
    external: true
