run-name: 'Deploy to ${{ github.event.inputs.environment }}: ${{ github.event.inputs.version }}'

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        options:
        - tst
        - stg
        - prd
        - acc
      version:
        description: Version
        required: true

jobs:
  deploy_start_slack:
    if: github.repository_owner == 'Informatievlaanderen'
    name: Deploy started
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    steps:
    - name: Parse repository name
      run: echo REPOSITORY_NAME=$(echo ""$GITHUB_REPOSITORY"" | awk -F / '{print $2}' | sed -e ""s/:refs//"") >> $GITHUB_ENV
      shell: bash

    - name: Uppercase environment
      run: echo "ENVIRONMENT_UPPER=${ENVIRONMENT,,}" >>${GITHUB_ENV}
      with:
        ENVIRONMENT: ${{ github.event.inputs.environment }}

    - name: Notify deployment started
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: '#team-wegenregister-dev'
        slack-message: Deployment of road-registry ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }} has started
      env:
        SLACK_BOT_TOKEN: ${{ secrets.VBR_SLACK_BOT_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.VBR_NOTIFIER_CHANNEL_NAME }}
        REPOSITORY_NAME: ${{ env.REPOSITORY_NAME }}

  deploy:
    if: github.repository_owner == 'Informatievlaanderen'
    needs: [deploy_start_slack]
    name: Deploy services
    runs-on: ubuntu-latest
    strategy:
       matrix: 
         services: [
          'road-registry-adminhost',
          'road-registry-backoffice-commandhost',
          'road-registry-backoffice-messaginghost-sqs',
          'road-registry-backoffice-eventhost',
          'road-registry-backoffice-extracthost',
          'road-registry-backoffice-api',
          'road-registry-backoffice-ui',
          'road-registry-product-projectionhost',
          'road-registry-wms-projectionhost',
          'road-registry-wfs-projectionhost',
          'road-registry-editor-projectionhost',
          'road-registry-syndication-projectionhost',
          'road-registry-projector',
          'road-registry-producer-snapshot-projectionhost',
          'road-registry-streetnameconsumer-projectionhost'
        ]

    steps:
    - name: CD services
      env:
        BUILD_URL: ${{ secrets.VBR_AWS_BUILD_API }}/${{matrix.services}}
        STATUS_URL: ${{ secrets.VBR_AWS_BUILD_STATUS_API }}/${{matrix.services}}
      uses: informatievlaanderen/awscurl-polling-action/polling-action@main
      with:
        environment: ${{ github.event.inputs.environment }}
        version: ${{ github.event.inputs.version }}
        status-url: $STATUS_URL
        deploy-url: $BUILD_URL
        access-key: ${{ secrets.VBR_AWS_BUILD_USER_ACCESS_KEY_ID }}
        secret-key: ${{ secrets.VBR_AWS_BUILD_USER_SECRET_ACCESS_KEY }}
        region: eu-west-1
        interval: 2

    - name: output CD services
      shell: bash
      run: |
        echo build-uuid: ${{ steps.awscurl-polling-action.outputs.build-uuid }}
        echo Status: ${{ steps.awscurl-polling-action.outputs.status }}
        echo ${{ steps.awscurl-polling-action.outputs.final-message }}

  deploy_lambda:
    if: github.repository_owner == 'Informatievlaanderen'
    needs: [deploy]
    name: Deploy Lambda(s)
    runs-on: ubuntu-latest

    steps:
    - name: CD Lambda(s) Configure credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        aws-access-key-id: ${{ secrets[format('VBR_AWS_ACCESS_KEY_ID_{0}', env.ENVIRONMENT_UPPER)] }}
        aws-secret-access-key: ${{ secrets[format('VBR_AWS_SECRET_ACCESS_KEY_{0}', env.ENVIRONMENT_UPPER)] }}
        aws-region: ${{ secrets[format('VBR_AWS_REGION_{0}', env.ENVIRONMENT_UPPER)] }}
        
    - name: Prepare Lambda(s)
      shell: bash
      run: |
        aws s3 cp s3://s3-vbr-$ENVIRONMENT-basisregisters-lam-wr-sqsbackofficehandlerfunction/$VERSION/lambda.zip s3://s3-vbr-$ENVIRONMENT-basisregisters-lam-wr-sqsbackofficehandlerfunction/lambda.zip --copy-props none
        aws s3 cp s3://s3-vbr-$ENVIRONMENT-basisregisters-lam-wr-sqssnapshothandlerfunction/$VERSION/lambda.zip s3://s3-vbr-$ENVIRONMENT-basisregisters-lam-wr-sqssnapshothandlerfunction/lambda.zip --copy-props none
      env:
        ENVIRONMENT: ${{ github.event.inputs.environment == 'tst' && 'test' || github.event.inputs.environment }}
        VERSION: ${{ github.event.inputs.version }}
        
    - name: Promote Lambda(s)
      shell: bash
      run: |
        docker pull ghcr.io/okigan/awscurl:latest
        
        docker run --rm okigan/awscurl --access_key $ACCESS_KEY_ID --secret_key $SECRET_ACCESS_KEY_ID --region $REGION -X POST -d '{ "functionName": "wr-sqsbackofficehandlerfunction", "project": "basisregisters", "domain": "basisregisters" }' $PROMOTEURL/$ENVIRONMENT
        docker run --rm okigan/awscurl --access_key $ACCESS_KEY_ID --secret_key $SECRET_ACCESS_KEY_ID --region $REGION -X POST -d '{ "functionName": "wr-sqssnapshothandlerfunction", "project": "basisregisters", "domain": "basisregisters" }' $PROMOTEURL/$ENVIRONMENT
      env:
        ACCESS_KEY_ID: ${{ secrets[format('VBR_AWS_ACCESS_KEY_ID_{0}', env.ENVIRONMENT_UPPER)] }}
        SECRET_ACCESS_KEY_ID: ${{ secrets[format('VBR_AWS_SECRET_ACCESS_KEY_{0}', env.ENVIRONMENT_UPPER)] }}
        ENVIRONMENT: ${{ github.event.inputs.environment == 'tst' && 'test' || github.event.inputs.environment }}
        REGION: ${{ secrets[format('VBR_AWS_REGION_{0}', env.ENVIRONMENT_UPPER)] }}
        PROMOTEURL: ${{ secrets.VBR_AWS_PROMOTE_LAMBDA_BASEURL }}

  deploy_finish_slack:
    if: github.repository_owner == 'Informatievlaanderen'
    needs: [deploy_lambda]
    name: Deploy finished
    runs-on: ubuntu-latest

    steps:
    - name: Parse repository name
      run: echo REPOSITORY_NAME=$(echo ""$GITHUB_REPOSITORY"" | awk -F / '{print $2}' | sed -e ""s/:refs//"") >> $GITHUB_ENV
      shell: bash

    - name: Notify deployment finished
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: '#team-wegenregister-dev'
        slack-message: Deployment of road-registry ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }} has finished
      env:
        SLACK_BOT_TOKEN: ${{ secrets.VBR_SLACK_BOT_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.VBR_NOTIFIER_CHANNEL_NAME }}
        REPOSITORY_NAME: ${{ env.REPOSITORY_NAME }}
