name: 4. Single Deploy
run-name: "Deploy ${{ inputs.service }} to ${{ inputs.environment }}: ${{ inputs.version }}"

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        options:
          - test
          - stg
          - prd
        required: true
      version:
        description: Version
        required: true
      service:
        type: choice
        description: Select the service to deploy
        options:
          - backoffice-api
          - backoffice-commandhost
          - backoffice-eventhost
          - backoffice-extracthost
          - backoffice-ui
          - editor-projectionhost
          - producer-snapshot-projectionhost
          - product-projectionhost
          - projector
          - synchost
          - wfs-projectionhost
          - wms-projectionhost
          - adminhost
          - jobs-processor
          - product-publishhost
          - lambdas
        required: true

permissions:
  id-token: write

jobs:
  deploy_start_slack:
    if: github.repository_owner == 'Informatievlaanderen' && (github.event.inputs.service != '')
    name: Deploy started
    runs-on: ubuntu-latest

    steps:
      - name: Notify deployment started
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ secrets.VBR_SLACK_BOT_TOKEN }}
          payload: |
            channel: '#team-dinosaur-dev'
            text: 'Deployment of ${{ github.event.inputs.service }} ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }} has started. View run at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'

  deploy_services:
    if: github.repository_owner == 'Informatievlaanderen' && github.event.inputs.service != 'lambdas'
    needs: [deploy_start_slack]
    name: Deploy service
    uses: informatievlaanderen/build-pipeline/.github/workflows/deploy-v4.1.yml@main
    strategy:
      matrix:
        services: ["${{github.event.inputs.service}}"]
    with:
      environment: ${{ github.event.inputs.environment }}
      service-name: ${{ matrix.services }}
      application: ${{ matrix.services }}
      version: ${{ github.event.inputs.version }}
      domain: 'road'
      project: 'grawr'
      use-subfolder: true
    secrets: inherit

  deploy_lambda:
    if: github.repository_owner == 'Informatievlaanderen' && github.event.inputs.service == 'lambdas'
    needs: [deploy_start_slack]
    name: Deploy lambda(s)
    uses: informatievlaanderen/build-pipeline/.github/workflows/deploy-v4.1.yml@main
    strategy:
      matrix:
        functions: [
          'lambda-sqsbackofficefunction',
          'lambda-sqssnapshotfunction'
        ]
    with:
      deploy-target: 'lambda'
      environment: ${{ github.event.inputs.environment }}
      service-name: ${{ matrix.functions }}
      application: 'lambda'
      version: ${{ github.event.inputs.version }}
      domain: 'road'
      project: 'grawr'
      use-subfolder: true
    secrets: inherit

  deploy_finish_slack:
    if: github.repository_owner == 'Informatievlaanderen'
    needs: [deploy_services, deploy_lambda]
    name: Notify deployment succeeded
    runs-on: ubuntu-latest

    steps:
      - name: Notify deployment succeeded
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ secrets.VBR_SLACK_BOT_TOKEN }}
          payload: |
            channel: '#team-dinosaur-dev'
            text: ':white_check_mark: Deployment of ${{ github.event.inputs.service }} ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }} has finished.'

  deploy_nothing_slack:
    if: github.repository_owner == 'Informatievlaanderen' && (github.event.inputs.service == '')
    needs: [deploy_services, deploy_lambda]
    name: Notify deployment cancelled
    runs-on: ubuntu-latest

    steps:
      - name: Notify deployment cancelled
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ secrets.VBR_SLACK_BOT_TOKEN }}
          payload: |
            channel: '#team-dinosaur-dev'
            text: ':x: No service/task/lambda was selected to be deployed.'

  deployment_notify_failure:
    if: ${{ github.repository_owner == 'Informatievlaanderen' && failure() }}
    name: Notify deployment failed
    runs-on: ubuntu-latest
    needs: [deploy_services, deploy_lambda]
    steps:
      - name: Notify deployment failed
        id: slack
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ secrets.VBR_SLACK_BOT_TOKEN }}
          payload: |
            channel: '#team-dinosaur-dev'
            text: ':x: Deployment of road-registry ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }} has failed. View run at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
