name: System healthcheck

on:
  workflow_dispatch:

concurrency: Release

jobs:

  system_healthcheck:
    if: github.repository_owner == 'Informatievlaanderen'
    name: Sytem healthcheck
    runs-on: ubuntu-latest

    steps:
    - name: Run
      run: |
        docker pull ghcr.io/okigan/awscurl:latest
        
        response=$(docker run --rm okigan/awscurl --access_key $ACCESS_KEY_ID --secret_key $SECRET_ACCESS_KEY_ID --region $REGION -X POST $BACKOFFICE_API_URL/v1/system/healthcheck -H "x-api-key: $ROAD_API_KEY" --fail)
        
        if [ $? -ne 0 ]; then
          exit 1
        fi

        echo "Response: $response"

        if echo "$response" | grep -q "unhealthy"; then
          echo "System is unhealthy"
          exit 1
        fi

        echo "System is healthy"
      shell: bash
      env:
        ACCESS_KEY_ID: ${{ secrets.VBR_AWS_ACCESS_KEY_ID_DEVOPS }}
        SECRET_ACCESS_KEY_ID: ${{ secrets.VBR_AWS_SECRET_ACCESS_KEY_DEVOPS }}
        REGION: ${{ secrets.VBR_AWS_REGION_PRD }}
        ROAD_API_KEY: ${{ secrets.HEALTHCHECK_APIKEY }}
        BACKOFFICE_API_URL: ${{ vars.BACKOFFICE_API_URL_TST }}