name: Release V2 Beta

on:
  workflow_dispatch:

concurrency: Release

jobs:
  set-release-version:
    if: github.repository_owner == 'Informatievlaanderen'
    name: Decide next version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}

    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1

      - name: Node version
        shell: bash
        run: node --version

      - name: Install NPM dependencies
        shell: bash
        run: npm ci
        env:
          NPM_TOKEN: ${{ secrets.VBR_WEBCOMP_NPM_TOKEN }}

      - name: Run Semantic Release Dry-Run
        shell: bash
        run: npx semantic-release --dry-run
        env:
          BUILD_DOCKER_REGISTRY: ${{ secrets.VBR_BUILD_DOCKER_REGISTRY_TST }}
          GITHUB_TOKEN: ${{ secrets.VBR_GIT_RELEASE_TOKEN }}
          GIT_COMMIT: ${{ github.sha }}
          GIT_USERNAME: ${{ secrets.VBR_GIT_USER }}
          GIT_AUTHOR_NAME: ${{ secrets.VBR_GIT_USER }}
          GIT_AUTHOR_EMAIL: ${{ secrets.VBR_GIT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.VBR_GIT_USER }}
          GIT_COMMITTER_EMAIL: ${{ secrets.VBR_GIT_EMAIL }}
          GIT_EMAIL: ${{ secrets.VBR_GIT_EMAIL }}
          NPM_TOKEN: ${{ secrets.VBR_WEBCOMP_NPM_TOKEN }}
          SA_PASSWORD: E@syP@ssw0rd
          CI: true

      - name: Set Release Version
        id: set-version
        run: |
            [ ! -f semver ] && echo none > semver
            echo $(cat semver)
            echo RELEASE_VERSION=$(cat semver) >> $GITHUB_ENV
        shell: bash
